# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 684da12205f96e3d498021739802312addb599c0590295179fb43d7203fb7af7b3cdd4b977a888fe4fded2932e3dd5b7bf8579841a9bb87217efb980ae7f1068

test:
  secret_key_base: ec458a4826d689205a529a7e0a4026b06ccaee1ae77f14a14e49e4c3a47e177ea8a15b69268e6ad8299b6f6f4b1a5b9758ab4779ee6bd37fdae03a5549d57e66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  